version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx_server:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: elixir_micro
    command: bash -c "mix phx.server"
    volumes:
      - .:/opt/application
    ports:
      - 4000:4000
    restart: always
